server:
  port: 8761

spring:
  application:
    name: eureka-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false #false for test & development
    eviction-interval-timer-in-ms: 3000 # Heart beat rate & development